type Env = {
  BASE_URL: string
  DATABASE_URL: string
  GOD_MODE_API_KEY: string
  GOD_MODE_HEADER: string
  JWT_SECRET: string
  MAIL_TRANSPORT_AUTH_PASSWORD: string
  MAIL_TRANSPORT_AUTH_USER: string
  MAIL_TRANSPORT_DEFAULT_FROM: string
  MAIL_TRANSPORT_HOST: string
  MAIL_TRANSPORT_PORT: number
  MAILTRAP_ACCOUNT_ID: string
  MAILTRAP_API_TOKEN: string
  MAILTRAP_INBOX_ID: string
  NEXT_PUBLIC_AUTH_COOKIE: string
  NODE_ENV: string
}

const env: Env = {
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL ?? 'http://localhost:3000',
  DATABASE_URL: process.env.NEXT_PUBLIC_DATABASE_URL ?? '',
  GOD_MODE_API_KEY: process.env.NEXT_PUBLIC_GOD_MODE_API_KEY ?? '$2y$10$zSmE.LHfsNNk9cgp3CvtH.0DOQrBZ7EGg34BWvsSdlHQ0TTXR5D8e',
  GOD_MODE_HEADER: process.env.NEXT_PUBLIC_GOD_MODE_HEADER ?? 'X-TODOS-API-KEY',
  JWT_SECRET: process.env.NEXT_PUBLIC_JWT_SECRET ?? 'secret',
  MAIL_TRANSPORT_AUTH_PASSWORD: process.env.NEXT_PUBLIC_MAIL_TRANSPORT_AUTH_PASSWORD ?? '',
  MAIL_TRANSPORT_AUTH_USER: process.env.NEXT_PUBLIC_MAIL_TRANSPORT_AUTH_USER ?? '',
  MAIL_TRANSPORT_DEFAULT_FROM: process.env.NEXT_PUBLIC_MAIL_TRANSPORT_DEFAULT_FROM ?? 'admin@todos.io',
  MAIL_TRANSPORT_HOST: process.env.NEXT_PUBLIC_MAIL_TRANSPORT_HOST ?? '',
  MAIL_TRANSPORT_PORT: parseInt(process.env.NEXT_PUBLIC_MAIL_TRANSPORT_PORT ?? ''),
  MAILTRAP_ACCOUNT_ID: process.env.NEXT_PUBLIC_MAILTRAP_ACCOUNT_ID ?? '',
  MAILTRAP_API_TOKEN: process.env.NEXT_PUBLIC_MAILTRAP_API_TOKEN ?? '',
  MAILTRAP_INBOX_ID: process.env.NEXT_PUBLIC_MAILTRAP_INBOX_ID ?? '',
  NEXT_PUBLIC_AUTH_COOKIE: process.env.NEXT_PUBLIC_AUTH_COOKIE ?? 'todos-auth',
  NODE_ENV: process.env.NODE_ENV ?? 'development',
}

export default env
