import Head from 'next/head'
import React from 'react'

import LoginForm from '../components/organisms/LoginForm'
import AppTemplate from '../components/templates/AppTemplate'
import useAuthentication from '../hooks/useAuthentication'

export default function Home() {
  const authState = useAuthentication()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <AppTemplate>
        {!authState.isAuth ? (
          <LoginForm />
        ) : (
          <></>
        )}
      </AppTemplate>
    </>
  )
}
