name: Newman

on: pull_request

jobs:
  api-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build
          npm start &
      - uses: matt-ball/newman-action@master
        with:
          collection: postman/tests.postman_collection.json
          environment: postman/local.postman_environment.json
