name: Newman

on: pull_request

jobs:
  api-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run dev &
      - name: Run
        run: |
          npm run newman:dev
